# Generated by Django 2.2.2 on 2019-07-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(default='Ordered', max_length=20),
            preserve_default=False,
        ),
    ]
